name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # 当主分支收到推送时触发

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Create Hello-world txt
      run: |
        echo helloworld > hello.txt
        
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 124.70.224.207
        username: uni
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "hello.txt"
        target: ~/
